<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'iletisim Gönderim',
	'heading' => 'Yeni Form Gönderimi',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'İşaretli',
		'checkbox_unchecked' => 'İşaretli Değil',
		'submitted_from' => 'Web sitesinden gönderilen form:%s',
		'submitted_by' => 'Ziyaretçi IP adresi:%s',
		'too_many_submissions' => 'Bu IP\'den son zamanlarda çok fazla sayıda gönderim yapıldı',
		'failed_to_send_email' => 'E-posta gönderilemedi',
		'invalid_reCAPTCHA_private_key' => 'Geçersiz reCAPTCHA özel anahtarı.',
		'invalid_reCAPTCHA2_private_key' => 'Geçersiz reCAPTCHA 2.0 özel anahtarı.',
		'invalid_reCAPTCHA2_server_response' => 'Geçersiz reCAPTCHA 2.0 sunucu yanıtı.',
		'invalid_field_type' => 'Bilinmeyen alan türü \'%s\'.',
		'invalid_form_config' => '\'%s\' alanında geçersiz yapılandırma var.',
		'unknown_method' => 'Bilinmeyen sunucu isteği yöntemi'
	),
	'email' => array(
		'from' => 'altinkaynak.mehmet@gmail.com',
		'to' => 'altinkaynak.mehmet@gmail.com'
	),
	'fields' => array(
		'custom_U299895' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Ad',
			'required' => true,
			'errors' => array(
				'required' => '\'Ad\' alanı gereklidir.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-posta',
			'required' => true,
			'errors' => array(
				'required' => '\'E-posta\' alanı gereklidir.',
				'format' => '\'E-posta\' alanında geçersiz e-posta var.'
			)
		),
		'custom_U299906' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Mesaj',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
